name: CI
on:
  push:
    branches: [ main ]

jobs:
  apigee-container-job:
    runs-on: ubuntu-latest
    container:
        # Specify the Docker image
      image: node:18  
      env:
        # Set environment variables
        NODE_ENV: development  
      ports:
        # Expose network ports
        - 80  
      volumes:
        - my_docker_volume:/volume_mount  
      options: --cpus 1  
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Check for dockerenv file
        run: (ls /.dockerenv && echo Found dockerenv) || (echo No dockerenv)

      - name: Run APIGEE X service commands
        run: |
          # Add your APIGEE X service commands here
          echo "Running APIGEE X service commands"
